In [7]:
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():
    t1 = time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = [x[i] + y[i] for i in range(len(x))]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = x + y
    return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()

t1 = pure_python_version()
t2 = numpy_version()
'''print(f 'Waktu running python adalah'{round(t1,4)}'detik. Waktu running versi numpy adalah'{round(t2,4)}'detik. Numpy di contoh ini'{(round((t1/t2),4))}'kali lebih cepat!')'''

TypeError: unsupported operand type(s) for +: 'range' and 'range'

In [8]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [16]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
np.random.rand(2)

array([0.08199419, 0.92297914])

In [26]:
np.random.rand(5,5)

array([[0.35454943, 0.95887007, 0.53845967, 0.15056032, 0.75114524],
       [0.41134677, 0.80677662, 0.35606397, 0.19486874, 0.08795443],
       [0.62732268, 0.67857116, 0.22673834, 0.17199357, 0.66636026],
       [0.34695615, 0.68334008, 0.9558593 , 0.39507351, 0.54901241],
       [0.56956409, 0.94847455, 0.23594379, 0.21605005, 0.54134021]])

In [27]:
np.random.randn(2)

array([-0.83896575,  0.02322869])

In [28]:
np.random.randn(5,5)

array([[ 0.71968833, -0.40854993,  0.20134987, -0.0270339 , -0.53268107],
       [-0.320229  ,  2.45562069,  0.53844808, -2.3765659 , -1.0497295 ],
       [ 0.51804853,  0.0263842 , -1.43047355, -0.44020675, -0.52412873],
       [-0.20741538,  0.2794626 ,  1.79438964,  0.58582009, -0.79080475],
       [ 0.53030206,  0.07292961, -1.88449451, -0.65495142,  2.0942133 ]])

In [29]:
np.random.randint(1,100)

1

In [30]:
np.random.randint(1,100,10)

array([80, 42, 16,  6, 75,  3, 82, 95, 37, 97])

In [31]:
my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

In [32]:
array_1d.shape

(3,)

In [33]:
array_2d.shape

(3, 3)

In [34]:
array_3d.shape

(3, 3, 3)

In [35]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
arr.reshape(1,25).shape

(1, 25)

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [40]:
arr.reshape(25,1).shape

(25, 1)

In [41]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
array_2d.reshape(-1).shape

(9,)

In [43]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [44]:
array_3d.reshape(-1).shape

(27,)

In [47]:
ranarr = np.random.randint(1,50,10)
ranarr

array([26, 10, 23, 48, 10, 24, 22, 16, 15, 24])

In [48]:
ranarr.max()

48

In [49]:
ranarr.argmax()

3

In [50]:
ranarr.min()

10

In [51]:
ranarr.argmin()

1

In [52]:
arr.dtype

dtype('int32')

In [53]:
arr1 = np.linspace(0,10,10)
arr1.dtype

dtype('float64')

In [67]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8]

8

In [70]:
arr[1:5]

array([1, 2, 3, 4])

In [71]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [72]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [73]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [74]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [76]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d[1]

array([20, 25, 30])

In [83]:
arr_2d[1][0]

20

In [84]:
arr_2d[1,0]

20

In [85]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [87]:
arr_2d[:,2]

array([15, 30, 45])

In [93]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
[arr[2],arr[5],arr[9]]

[2, 5, 9]

In [95]:
arr[[2,5,9]]

array([2, 5, 9])

In [96]:
arr[[5,9,2]]

array([5, 9, 2])

In [97]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [98]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [99]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [102]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [103]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [104]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])